on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: action-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build (x86_64)
        with:
          command: build
          args: --target=x86_64-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v3
        with:
          name: server-daemon-x86_64
          path: target/x86_64-unknown-linux-gnu/release/server-daemon